receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}

processors:
  batch: {}
  resource:
    attributes:
      - key: tenant.id
        value: "001"
        action: upsert

exporters:
  otlp:
    endpoint: 212.85.23.26:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [resource, batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp]

